name: Make Profiles

on:
  workflow_dispatch:
    inputs:
      debug_enabled:
        type: boolean
        description: 'With TMATE'
        required: false
        default: false
        
  schedule:
    - cron:  '0 0 * * 5'
  
  push:
    branches: [ "*" ]

env:
#   manjaroProfiles: manjaro-iso-profiles
  makeisoprofilesdir: biglinux-make-iso-profiles

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      
      # Tmate ##
      - name: Setup TMATE Session
        uses: mxschmitt/action-tmate@v3
        if: ${{ github.event.inputs.debug_enabled }}
      
#       - name: Clone ManjaroIsoProfile
#         shell: bash
#         run: |
#             # clone or Update git
#             if [ ! -d "$manjaroProfiles" ]; then
#               git clone https://gitlab.manjaro.org/profiles-and-settings/iso-profiles.git $manjaroProfiles
#             else
#               pushd $manjaroProfiles
#               git pull
#               popd
#             fi
         
#       - name: Make Base
#         shell: bash
#         run: |
#             # Copy files
#             cp $makeisoprofilesdir/base/profile.conf shared/
#             cp $makeisoprofilesdir/base/pacman-default.conf shared/
#             cp $makeisoprofilesdir/base/user-repos.conf shared/
            
      - name: Make Flavours
        shell: bash
        run: |
            ## make FLAVOURS ##
            for i in $(ls $makeisoprofilesdir | sed '/base/d'); do
                echo ""
                echo "MAKE $i"
                echo ""
                
#                 rsync -Cravzp --delete shared/ biglinux/$i
                
                # Remove Mhwd
                if [ -e "$makeisoprofilesdir/$i/Mhwd-remove" ]; then
                  grep -v -f $makeisoprofilesdir/$i/Mhwd-remove shared/Packages-Mhwd > shared/Packages-Mhwd.tmp
                  mv -f shared/Packages-Mhwd.tmp shared/Packages-Mhwd
                else
                  echo "no Remove Mhwd in $i"
                fi                
                
                # Remove Root
                if [ -e "$makeisoprofilesdir/$i/Root-remove" ]; then
                  grep -v -f "$makeisoprofilesdir/$i/Root-remove" shared/Packages-Root > shared/Packages-Root.tmp
                  mv -f shared/Packages-Root.tmp shared/Packages-Root
                else
                  echo "no Remove Root in $i"
                fi               
                
                # Run special commands
                if [ -e "$makeisoprofilesdir/$i/special-commands.sh" ]; then
                  bash -x $makeisoprofilesdir/$i/special-commands.sh
                fi
            done
          
      - name: Update github
        run: |
            git add --all
            git config --local user.email "41898282+github-actions[bot]@users.noreply.github.com"
            git config --local user.name "github-actions[bot]"
            if [ -n "$(git diff --staged --quiet || echo 'changes')" ]; then
              git commit -m "new profile"
              git push
            else
              echo "no changes to commit"
            fi

      - name: Push changes
        uses: ad-m/github-push-action@master
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          branch: ${{ github.ref }}
